name = "webcontrol-hq-api"
main = "worker/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "webcontrol-hq"
database_id = "e22c8e57-4550-4566-9937-cd7d51560b70"

[[d1_databases]]
binding = "RLDB"
database_name = "ratelimit-db"
database_id = "33fba40f-abcc-43b1-b931-04baca75462b"

[[d1_databases]]
binding = "RSDB"
database_name = "rechtschreibe-api-db"
database_id = "e774513c-23fe-48ab-a936-2e04df167ff6"

[vars]
ENVIRONMENT = "production"
# DASHBOARD_PASSWORD wird als Secret gesetzt, NICHT hier im File!
# Befehl: npx wrangler secret put DASHBOARD_PASSWORD
